// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActorCreate
 */
export type ActorCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birth Date
     */
    birth_date?: string | null;
};

/**
 * ActorPublic
 */
export type ActorPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birth Date
     */
    birth_date: string | null;
};

/**
 * ActorUpdate
 */
export type ActorUpdate = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
};

/**
 * ActorsPublic
 */
export type ActorsPublic = {
    /**
     * Actors
     */
    actors: Array<ActorPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DirectorCreate
 */
export type DirectorCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birth Date
     */
    birth_date?: string | null;
};

/**
 * DirectorPublic
 */
export type DirectorPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birth Date
     */
    birth_date: string | null;
};

/**
 * DirectorUpdate
 */
export type DirectorUpdate = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
};

/**
 * DirectorsPublic
 */
export type DirectorsPublic = {
    /**
     * Directors
     */
    directors: Array<DirectorPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * GenreCreate
 */
export type GenreCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * GenrePublic
 */
export type GenrePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * GenreUpdate
 */
export type GenreUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * GenresPublic
 */
export type GenresPublic = {
    /**
     * Genres
     */
    genres: Array<GenrePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MovieCreate
 *
 * Schema for creating a movie with its genres, actors, and directors.
 */
export type MovieCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Synopsis
     */
    synopsis: string;
    /**
     * Release Year
     */
    release_year: number;
    /**
     * Duration
     */
    duration: number;
    /**
     * Age Rating
     */
    age_rating: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17';
    /**
     * Poster Url
     */
    poster_url: string;
    /**
     * Trailer Url
     */
    trailer_url: string;
    /**
     * Genre Ids
     */
    genre_ids: Array<string>;
    /**
     * Actors
     */
    actors: Array<ActorCreate>;
    /**
     * Directors
     */
    directors: Array<DirectorCreate>;
};

/**
 * MoviePublic
 *
 * Public representation of a movie with its related genres, actors, and directors.
 */
export type MoviePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Synopsis
     */
    synopsis: string;
    /**
     * Release Year
     */
    release_year: number;
    /**
     * Duration
     */
    duration: number;
    /**
     * Age Rating
     */
    age_rating: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17';
    /**
     * Poster Url
     */
    poster_url: string;
    /**
     * Trailer Url
     */
    trailer_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Genres
     */
    genres: Array<GenrePublic>;
    /**
     * Actors
     */
    actors: Array<PersonSummary>;
    /**
     * Directors
     */
    directors: Array<PersonSummary>;
};

/**
 * MovieUpdate
 *
 * Schema for partially updating a movie and its relationships.
 */
export type MovieUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Synopsis
     */
    synopsis?: string | null;
    /**
     * Release Year
     */
    release_year?: number | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Age Rating
     */
    age_rating?: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17' | null;
    /**
     * Poster Url
     */
    poster_url?: string | null;
    /**
     * Trailer Url
     */
    trailer_url?: string | null;
    /**
     * Genre Ids
     */
    genre_ids?: Array<string> | null;
    /**
     * Actors
     */
    actors?: Array<ActorCreate> | null;
    /**
     * Directors
     */
    directors?: Array<DirectorCreate> | null;
};

/**
 * MovieWithRatingPublic
 *
 * Public movie representation including its average review rating.
 */
export type MovieWithRatingPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Synopsis
     */
    synopsis: string;
    /**
     * Release Year
     */
    release_year: number;
    /**
     * Duration
     */
    duration: number;
    /**
     * Age Rating
     */
    age_rating: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17';
    /**
     * Poster Url
     */
    poster_url: string;
    /**
     * Trailer Url
     */
    trailer_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Genres
     */
    genres: Array<GenrePublic>;
    /**
     * Actors
     */
    actors: Array<PersonSummary>;
    /**
     * Directors
     */
    directors: Array<PersonSummary>;
    /**
     * Average Rating
     */
    average_rating: number;
};

/**
 * MoviesPublic
 *
 * Response schema for a collection of movies with the total count.
 */
export type MoviesPublic = {
    /**
     * Movies
     */
    movies: Array<MoviePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MoviesWithRatingPublic
 *
 * Response schema for rated movies with the total count.
 */
export type MoviesWithRatingPublic = {
    /**
     * Movies
     */
    movies: Array<MovieWithRatingPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PersonSummary
 *
 * Compact actor or director representation used inside movie responses.
 */
export type PersonSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
    /**
     * Rating
     */
    rating: number;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * ReviewPublic
 */
export type ReviewPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Rating
     */
    rating: number;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Movie Id
     */
    movie_id: string;
};

/**
 * ReviewUpdate
 */
export type ReviewUpdate = {
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * ReviewsPublic
 */
export type ReviewsPublic = {
    /**
     * Reviews
     */
    reviews: Array<ReviewPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 *
 * Schema for the access token returned after successful authentication.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 *
 * Schema for changing the current user's password.
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Schema for public user registration.
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserOwnData
 *
 * Profile data available to the currently authenticated user.
 */
export type UserOwnData = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserPrivateData
 *
 * Private user account data available to administrators.
 */
export type UserPrivateData = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserPublic
 *
 * Public user data that may be exposed to other users.
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserUpdate
 *
 * Schema for admin-only user account updates.
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * UserUpdateMe
 *
 * Schema for updating the current user's profile.
 */
export type UserUpdateMe = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPrivateData
 *
 * Response schema for an admin user collection with the total count.
 */
export type UsersPrivateData = {
    /**
     * Users
     */
    users: Array<UserPrivateData>;
    /**
     * Count
     */
    count: number;
};

/**
 * UsersPublic
 *
 * Response schema for a public user collection with the total count.
 */
export type UsersPublic = {
    /**
     * Users
     */
    users: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserOwnData;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type usersGetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users';
};

export type usersGetUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetUsersError = usersGetUsersErrors[keyof usersGetUsersErrors];

export type usersGetUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersGetUsersResponse = usersGetUsersResponses[keyof usersGetUsersResponses];

export type usersRegisterUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserOwnData;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserOwnData;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeactivateUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/deactivate';
};

export type usersDeactivateUserMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeactivateUserMeResponse = usersDeactivateUserMeResponses[keyof usersDeactivateUserMeResponses];

export type usersGetUsersPrivateDadaData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users/admin';
};

export type usersGetUsersPrivateDadaErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetUsersPrivateDadaError = usersGetUsersPrivateDadaErrors[keyof usersGetUsersPrivateDadaErrors];

export type usersGetUsersPrivateDadaResponses = {
    /**
     * Successful Response
     */
    200: UsersPrivateData;
};

export type usersGetUsersPrivateDadaResponse = usersGetUsersPrivateDadaResponses[keyof usersGetUsersPrivateDadaResponses];

export type usersGetUserByEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/api/v1/users/email';
};

export type usersGetUserByEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetUserByEmailError = usersGetUserByEmailErrors[keyof usersGetUserByEmailErrors];

export type usersGetUserByEmailResponses = {
    /**
     * Successful Response
     */
    200: UserPrivateData;
};

export type usersGetUserByEmailResponse = usersGetUserByEmailResponses[keyof usersGetUserByEmailResponses];

export type usersGetUserByUsernameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/api/v1/users/username';
};

export type usersGetUserByUsernameErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetUserByUsernameError = usersGetUserByUsernameErrors[keyof usersGetUserByUsernameErrors];

export type usersGetUserByUsernameResponses = {
    /**
     * Successful Response
     */
    200: UserPrivateData;
};

export type usersGetUserByUsernameResponse = usersGetUserByUsernameResponses[keyof usersGetUserByUsernameResponses];

export type usersGetActiveUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users/active-users';
};

export type usersGetActiveUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetActiveUsersError = usersGetActiveUsersErrors[keyof usersGetActiveUsersErrors];

export type usersGetActiveUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPrivateData;
};

export type usersGetActiveUsersResponse = usersGetActiveUsersResponses[keyof usersGetActiveUsersResponses];

export type usersGetInactiveUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/users/inactive-users';
};

export type usersGetInactiveUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetInactiveUsersError = usersGetInactiveUsersErrors[keyof usersGetInactiveUsersErrors];

export type usersGetInactiveUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPrivateData;
};

export type usersGetInactiveUsersResponse = usersGetInactiveUsersResponses[keyof usersGetInactiveUsersResponses];

export type usersGetUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersGetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersGetUserByIdError = usersGetUserByIdErrors[keyof usersGetUserByIdErrors];

export type usersGetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPrivateData;
};

export type usersGetUserByIdResponse = usersGetUserByIdResponses[keyof usersGetUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPrivateData;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type usersDeactivateUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/deactivate';
};

export type usersDeactivateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeactivateUserError = usersDeactivateUserErrors[keyof usersDeactivateUserErrors];

export type usersDeactivateUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeactivateUserResponse = usersDeactivateUserResponses[keyof usersDeactivateUserResponses];

export type usersReactivateUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/reactivate';
};

export type usersReactivateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReactivateUserError = usersReactivateUserErrors[keyof usersReactivateUserErrors];

export type usersReactivateUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersReactivateUserResponse = usersReactivateUserResponses[keyof usersReactivateUserResponses];

export type genresGetGenresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/genres';
};

export type genresGetGenresResponses = {
    /**
     * Successful Response
     */
    200: GenresPublic;
};

export type genresGetGenresResponse = genresGetGenresResponses[keyof genresGetGenresResponses];

export type genresCreateGenreData = {
    body: GenreCreate;
    path?: never;
    query?: never;
    url: '/api/v1/genres';
};

export type genresCreateGenreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type genresCreateGenreError = genresCreateGenreErrors[keyof genresCreateGenreErrors];

export type genresCreateGenreResponses = {
    /**
     * Successful Response
     */
    201: GenrePublic;
};

export type genresCreateGenreResponse = genresCreateGenreResponses[keyof genresCreateGenreResponses];

export type genresDeleteGenreData = {
    body?: never;
    path: {
        /**
         * Genre Id
         */
        genre_id: string;
    };
    query?: never;
    url: '/api/v1/genres/{genre_id}';
};

export type genresDeleteGenreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type genresDeleteGenreError = genresDeleteGenreErrors[keyof genresDeleteGenreErrors];

export type genresDeleteGenreResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type genresDeleteGenreResponse = genresDeleteGenreResponses[keyof genresDeleteGenreResponses];

export type genresGetGenreData = {
    body?: never;
    path: {
        /**
         * Genre Id
         */
        genre_id: string;
    };
    query?: never;
    url: '/api/v1/genres/{genre_id}';
};

export type genresGetGenreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type genresGetGenreError = genresGetGenreErrors[keyof genresGetGenreErrors];

export type genresGetGenreResponses = {
    /**
     * Successful Response
     */
    200: GenrePublic;
};

export type genresGetGenreResponse = genresGetGenreResponses[keyof genresGetGenreResponses];

export type genresUpdateGenreData = {
    body: GenreUpdate;
    path: {
        /**
         * Genre Id
         */
        genre_id: string;
    };
    query?: never;
    url: '/api/v1/genres/{genre_id}';
};

export type genresUpdateGenreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type genresUpdateGenreError = genresUpdateGenreErrors[keyof genresUpdateGenreErrors];

export type genresUpdateGenreResponses = {
    /**
     * Successful Response
     */
    200: GenrePublic;
};

export type genresUpdateGenreResponse = genresUpdateGenreResponses[keyof genresUpdateGenreResponses];

export type actorsGetActorsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/actors';
};

export type actorsGetActorsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actorsGetActorsError = actorsGetActorsErrors[keyof actorsGetActorsErrors];

export type actorsGetActorsResponses = {
    /**
     * Successful Response
     */
    200: ActorsPublic;
};

export type actorsGetActorsResponse = actorsGetActorsResponses[keyof actorsGetActorsResponses];

export type actorsCreateActorData = {
    body: ActorCreate;
    path?: never;
    query?: never;
    url: '/api/v1/actors';
};

export type actorsCreateActorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actorsCreateActorError = actorsCreateActorErrors[keyof actorsCreateActorErrors];

export type actorsCreateActorResponses = {
    /**
     * Successful Response
     */
    201: ActorPublic;
};

export type actorsCreateActorResponse = actorsCreateActorResponses[keyof actorsCreateActorResponses];

export type actorsDeleteActorData = {
    body?: never;
    path: {
        /**
         * Actor Id
         */
        actor_id: string;
    };
    query?: never;
    url: '/api/v1/actors/{actor_id}';
};

export type actorsDeleteActorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actorsDeleteActorError = actorsDeleteActorErrors[keyof actorsDeleteActorErrors];

export type actorsDeleteActorResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type actorsDeleteActorResponse = actorsDeleteActorResponses[keyof actorsDeleteActorResponses];

export type actorsGetActorData = {
    body?: never;
    path: {
        /**
         * Actor Id
         */
        actor_id: string;
    };
    query?: never;
    url: '/api/v1/actors/{actor_id}';
};

export type actorsGetActorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actorsGetActorError = actorsGetActorErrors[keyof actorsGetActorErrors];

export type actorsGetActorResponses = {
    /**
     * Successful Response
     */
    200: ActorPublic;
};

export type actorsGetActorResponse = actorsGetActorResponses[keyof actorsGetActorResponses];

export type actorsUpdateActorData = {
    body: ActorUpdate;
    path: {
        /**
         * Actor Id
         */
        actor_id: string;
    };
    query?: never;
    url: '/api/v1/actors/{actor_id}';
};

export type actorsUpdateActorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actorsUpdateActorError = actorsUpdateActorErrors[keyof actorsUpdateActorErrors];

export type actorsUpdateActorResponses = {
    /**
     * Successful Response
     */
    200: ActorPublic;
};

export type actorsUpdateActorResponse = actorsUpdateActorResponses[keyof actorsUpdateActorResponses];

export type directorsGetDirectorsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/directors';
};

export type directorsGetDirectorsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type directorsGetDirectorsError = directorsGetDirectorsErrors[keyof directorsGetDirectorsErrors];

export type directorsGetDirectorsResponses = {
    /**
     * Successful Response
     */
    200: DirectorsPublic;
};

export type directorsGetDirectorsResponse = directorsGetDirectorsResponses[keyof directorsGetDirectorsResponses];

export type directorsCreateDirectorData = {
    body: DirectorCreate;
    path?: never;
    query?: never;
    url: '/api/v1/directors';
};

export type directorsCreateDirectorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type directorsCreateDirectorError = directorsCreateDirectorErrors[keyof directorsCreateDirectorErrors];

export type directorsCreateDirectorResponses = {
    /**
     * Successful Response
     */
    201: DirectorPublic;
};

export type directorsCreateDirectorResponse = directorsCreateDirectorResponses[keyof directorsCreateDirectorResponses];

export type directorsDeleteDirectorData = {
    body?: never;
    path: {
        /**
         * Director Id
         */
        director_id: string;
    };
    query?: never;
    url: '/api/v1/directors/{director_id}';
};

export type directorsDeleteDirectorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type directorsDeleteDirectorError = directorsDeleteDirectorErrors[keyof directorsDeleteDirectorErrors];

export type directorsDeleteDirectorResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type directorsDeleteDirectorResponse = directorsDeleteDirectorResponses[keyof directorsDeleteDirectorResponses];

export type directorsGetDirectorData = {
    body?: never;
    path: {
        /**
         * Director Id
         */
        director_id: string;
    };
    query?: never;
    url: '/api/v1/directors/{director_id}';
};

export type directorsGetDirectorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type directorsGetDirectorError = directorsGetDirectorErrors[keyof directorsGetDirectorErrors];

export type directorsGetDirectorResponses = {
    /**
     * Successful Response
     */
    200: DirectorPublic;
};

export type directorsGetDirectorResponse = directorsGetDirectorResponses[keyof directorsGetDirectorResponses];

export type directorsUpdateDirectorData = {
    body: DirectorUpdate;
    path: {
        /**
         * Director Id
         */
        director_id: string;
    };
    query?: never;
    url: '/api/v1/directors/{director_id}';
};

export type directorsUpdateDirectorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type directorsUpdateDirectorError = directorsUpdateDirectorErrors[keyof directorsUpdateDirectorErrors];

export type directorsUpdateDirectorResponses = {
    /**
     * Successful Response
     */
    200: DirectorPublic;
};

export type directorsUpdateDirectorResponse = directorsUpdateDirectorResponses[keyof directorsUpdateDirectorResponses];

export type reviewsGetReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/reviews';
};

export type reviewsGetReviewsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsGetReviewsError = reviewsGetReviewsErrors[keyof reviewsGetReviewsErrors];

export type reviewsGetReviewsResponses = {
    /**
     * Successful Response
     */
    200: ReviewsPublic;
};

export type reviewsGetReviewsResponse = reviewsGetReviewsResponses[keyof reviewsGetReviewsResponses];

export type reviewsGetAdminReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * User Id
         */
        user_id?: string | null;
        /**
         * Movie Id
         */
        movie_id?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/reviews/admin';
};

export type reviewsGetAdminReviewsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsGetAdminReviewsError = reviewsGetAdminReviewsErrors[keyof reviewsGetAdminReviewsErrors];

export type reviewsGetAdminReviewsResponses = {
    /**
     * Successful Response
     */
    200: ReviewsPublic;
};

export type reviewsGetAdminReviewsResponse = reviewsGetAdminReviewsResponses[keyof reviewsGetAdminReviewsResponses];

export type reviewsDeleteReviewData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/v1/reviews/{review_id}';
};

export type reviewsDeleteReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsDeleteReviewError = reviewsDeleteReviewErrors[keyof reviewsDeleteReviewErrors];

export type reviewsDeleteReviewResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type reviewsDeleteReviewResponse = reviewsDeleteReviewResponses[keyof reviewsDeleteReviewResponses];

export type reviewsGetReviewData = {
    body?: never;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/v1/reviews/{review_id}';
};

export type reviewsGetReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsGetReviewError = reviewsGetReviewErrors[keyof reviewsGetReviewErrors];

export type reviewsGetReviewResponses = {
    /**
     * Successful Response
     */
    200: ReviewPublic;
};

export type reviewsGetReviewResponse = reviewsGetReviewResponses[keyof reviewsGetReviewResponses];

export type reviewsUpdateReviewData = {
    body: ReviewUpdate;
    path: {
        /**
         * Review Id
         */
        review_id: string;
    };
    query?: never;
    url: '/api/v1/reviews/{review_id}';
};

export type reviewsUpdateReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsUpdateReviewError = reviewsUpdateReviewErrors[keyof reviewsUpdateReviewErrors];

export type reviewsUpdateReviewResponses = {
    /**
     * Successful Response
     */
    200: ReviewPublic;
};

export type reviewsUpdateReviewResponse = reviewsUpdateReviewResponses[keyof reviewsUpdateReviewResponses];

export type reviewsGetReviewsByMovieData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/reviews/movie/{movie_id}';
};

export type reviewsGetReviewsByMovieErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsGetReviewsByMovieError = reviewsGetReviewsByMovieErrors[keyof reviewsGetReviewsByMovieErrors];

export type reviewsGetReviewsByMovieResponses = {
    /**
     * Successful Response
     */
    200: ReviewsPublic;
};

export type reviewsGetReviewsByMovieResponse = reviewsGetReviewsByMovieResponses[keyof reviewsGetReviewsByMovieResponses];

export type reviewsCreateReviewData = {
    body: ReviewCreate;
    path: {
        /**
         * Movie Id
         */
        movie_id: string;
    };
    query?: never;
    url: '/api/v1/reviews/movie/{movie_id}';
};

export type reviewsCreateReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsCreateReviewError = reviewsCreateReviewErrors[keyof reviewsCreateReviewErrors];

export type reviewsCreateReviewResponses = {
    /**
     * Successful Response
     */
    201: ReviewPublic;
};

export type reviewsCreateReviewResponse = reviewsCreateReviewResponses[keyof reviewsCreateReviewResponses];

export type reviewsGetReviewsByUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/reviews/user/{user_id}';
};

export type reviewsGetReviewsByUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsGetReviewsByUserError = reviewsGetReviewsByUserErrors[keyof reviewsGetReviewsByUserErrors];

export type reviewsGetReviewsByUserResponses = {
    /**
     * Successful Response
     */
    200: ReviewsPublic;
};

export type reviewsGetReviewsByUserResponse = reviewsGetReviewsByUserResponses[keyof reviewsGetReviewsByUserResponses];

export type moviesGetMoviesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies';
};

export type moviesGetMoviesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesError = moviesGetMoviesErrors[keyof moviesGetMoviesErrors];

export type moviesGetMoviesResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesResponse = moviesGetMoviesResponses[keyof moviesGetMoviesResponses];

export type moviesCreateMovieData = {
    body: MovieCreate;
    path?: never;
    query?: never;
    url: '/api/v1/movies';
};

export type moviesCreateMovieErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesCreateMovieError = moviesCreateMovieErrors[keyof moviesCreateMovieErrors];

export type moviesCreateMovieResponses = {
    /**
     * Successful Response
     */
    201: MoviePublic;
};

export type moviesCreateMovieResponse = moviesCreateMovieResponses[keyof moviesCreateMovieResponses];

export type moviesGetMoviesByTitleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Title
         */
        title: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/title';
};

export type moviesGetMoviesByTitleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByTitleError = moviesGetMoviesByTitleErrors[keyof moviesGetMoviesByTitleErrors];

export type moviesGetMoviesByTitleResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByTitleResponse = moviesGetMoviesByTitleResponses[keyof moviesGetMoviesByTitleResponses];

export type moviesGetMoviesByReleaseYearData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Release Year
         */
        release_year: number;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/release-year';
};

export type moviesGetMoviesByReleaseYearErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByReleaseYearError = moviesGetMoviesByReleaseYearErrors[keyof moviesGetMoviesByReleaseYearErrors];

export type moviesGetMoviesByReleaseYearResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByReleaseYearResponse = moviesGetMoviesByReleaseYearResponses[keyof moviesGetMoviesByReleaseYearResponses];

export type moviesGetMoviesByAgeRatingData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Age Rating
         */
        age_rating: 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17';
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/age-rating';
};

export type moviesGetMoviesByAgeRatingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByAgeRatingError = moviesGetMoviesByAgeRatingErrors[keyof moviesGetMoviesByAgeRatingErrors];

export type moviesGetMoviesByAgeRatingResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByAgeRatingResponse = moviesGetMoviesByAgeRatingResponses[keyof moviesGetMoviesByAgeRatingResponses];

export type moviesGetMoviesByGenreData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Genre
         */
        genre: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/genre';
};

export type moviesGetMoviesByGenreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByGenreError = moviesGetMoviesByGenreErrors[keyof moviesGetMoviesByGenreErrors];

export type moviesGetMoviesByGenreResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByGenreResponse = moviesGetMoviesByGenreResponses[keyof moviesGetMoviesByGenreResponses];

export type moviesGetMoviesByActorData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Actor
         */
        actor: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/actor';
};

export type moviesGetMoviesByActorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByActorError = moviesGetMoviesByActorErrors[keyof moviesGetMoviesByActorErrors];

export type moviesGetMoviesByActorResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByActorResponse = moviesGetMoviesByActorResponses[keyof moviesGetMoviesByActorResponses];

export type moviesGetMoviesByDirectorData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Director
         */
        director: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/director';
};

export type moviesGetMoviesByDirectorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByDirectorError = moviesGetMoviesByDirectorErrors[keyof moviesGetMoviesByDirectorErrors];

export type moviesGetMoviesByDirectorResponses = {
    /**
     * Successful Response
     */
    200: MoviesPublic;
};

export type moviesGetMoviesByDirectorResponse = moviesGetMoviesByDirectorResponses[keyof moviesGetMoviesByDirectorResponses];

export type moviesGetMoviesByMinRatingData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Min Rating
         */
        min_rating: number;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/min-rating';
};

export type moviesGetMoviesByMinRatingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesByMinRatingError = moviesGetMoviesByMinRatingErrors[keyof moviesGetMoviesByMinRatingErrors];

export type moviesGetMoviesByMinRatingResponses = {
    /**
     * Successful Response
     */
    200: MoviesWithRatingPublic;
};

export type moviesGetMoviesByMinRatingResponse = moviesGetMoviesByMinRatingResponses[keyof moviesGetMoviesByMinRatingResponses];

export type moviesGetMoviesOrderedByRatingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/movies/rating';
};

export type moviesGetMoviesOrderedByRatingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMoviesOrderedByRatingError = moviesGetMoviesOrderedByRatingErrors[keyof moviesGetMoviesOrderedByRatingErrors];

export type moviesGetMoviesOrderedByRatingResponses = {
    /**
     * Successful Response
     */
    200: MoviesWithRatingPublic;
};

export type moviesGetMoviesOrderedByRatingResponse = moviesGetMoviesOrderedByRatingResponses[keyof moviesGetMoviesOrderedByRatingResponses];

export type moviesGetTopRatedMoviesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/movies/top-rated';
};

export type moviesGetTopRatedMoviesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetTopRatedMoviesError = moviesGetTopRatedMoviesErrors[keyof moviesGetTopRatedMoviesErrors];

export type moviesGetTopRatedMoviesResponses = {
    /**
     * Successful Response
     */
    200: MoviesWithRatingPublic;
};

export type moviesGetTopRatedMoviesResponse = moviesGetTopRatedMoviesResponses[keyof moviesGetTopRatedMoviesResponses];

export type moviesDeleteMovieData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: string;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type moviesDeleteMovieErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesDeleteMovieError = moviesDeleteMovieErrors[keyof moviesDeleteMovieErrors];

export type moviesDeleteMovieResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type moviesDeleteMovieResponse = moviesDeleteMovieResponses[keyof moviesDeleteMovieResponses];

export type moviesGetMovieData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: string;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type moviesGetMovieErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesGetMovieError = moviesGetMovieErrors[keyof moviesGetMovieErrors];

export type moviesGetMovieResponses = {
    /**
     * Successful Response
     */
    200: MoviePublic;
};

export type moviesGetMovieResponse = moviesGetMovieResponses[keyof moviesGetMovieResponses];

export type moviesUpdateMovieData = {
    body: MovieUpdate;
    path: {
        /**
         * Movie Id
         */
        movie_id: string;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type moviesUpdateMovieErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type moviesUpdateMovieError = moviesUpdateMovieErrors[keyof moviesUpdateMovieErrors];

export type moviesUpdateMovieResponses = {
    /**
     * Successful Response
     */
    200: MoviePublic;
};

export type moviesUpdateMovieResponse = moviesUpdateMovieResponses[keyof moviesUpdateMovieResponses];
