/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutMoviesMovieIdRouteImport } from './routes/_layout/movies.$movieId'
import { Route as LayoutMoviesCreateRouteImport } from './routes/_layout/movies.create'
import { Route as LayoutMoviesMovieIdEditRouteImport } from './routes/_layout/movies.$movieId_.edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesMovieIdRoute = LayoutMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesCreateRoute = LayoutMoviesCreateRouteImport.update({
  id: '/movies/create',
  path: '/movies/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesMovieIdEditRoute = LayoutMoviesMovieIdEditRouteImport.update({
  id: '/movies/$movieId_/edit',
  path: '/movies/$movieId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/movies/create': typeof LayoutMoviesCreateRoute
  '/movies/$movieId/edit': typeof LayoutMoviesMovieIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/movies/create': typeof LayoutMoviesCreateRoute
  '/movies/$movieId/edit': typeof LayoutMoviesMovieIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/_layout/movies/create': typeof LayoutMoviesCreateRoute
  '/_layout/movies/$movieId_/edit': typeof LayoutMoviesMovieIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/users'
    | '/movies/$movieId'
    | '/movies/create'
    | '/movies/$movieId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/settings'
    | '/users'
    | '/'
    | '/movies/$movieId'
    | '/movies/create'
    | '/movies/$movieId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/settings'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/movies/$movieId'
    | '/_layout/movies/create'
    | '/_layout/movies/$movieId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$movieId': {
      id: '/_layout/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof LayoutMoviesMovieIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/create': {
      id: '/_layout/movies/create'
      path: '/movies/create'
      fullPath: '/movies/create'
      preLoaderRoute: typeof LayoutMoviesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$movieId_/edit': {
      id: '/_layout/movies/$movieId_/edit'
      path: '/movies/$movieId/edit'
      fullPath: '/movies/$movieId/edit'
      preLoaderRoute: typeof LayoutMoviesMovieIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMoviesMovieIdRoute: typeof LayoutMoviesMovieIdRoute
  LayoutMoviesCreateRoute: typeof LayoutMoviesCreateRoute
  LayoutMoviesMovieIdEditRoute: typeof LayoutMoviesMovieIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMoviesMovieIdRoute: LayoutMoviesMovieIdRoute,
  LayoutMoviesCreateRoute: LayoutMoviesCreateRoute,
  LayoutMoviesMovieIdEditRoute: LayoutMoviesMovieIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
